### ISSUE TITLE
HLS video not working

### ISSUE THREAD

**Issue by ShaimaaHamdan** [alfg/mediacast#5]
Hello , I setup your sample and i tried following url 
https://6954a71498174453877a15012532b59c.azureedge.net/085b9f90-988a-42be-82ee-b2961df81c23/62f9b6f9-8221-4644-b198-9f9f718e881f.ism/manifest(format=m3u8-aapl)

and it is not working for me do you have any idea why it is not working ? although i tired it with others videos and it was working perfectly ?

thanks

**Comment by alfg** [comment]
Hi @ShaimaaHamdan, 

It may be due to the url structure of that playlist. I select the adaptive streaming format by the extension:
https://github.com/alfg/mediacast/blob/master/src/components/receiver/Receiver.vue#L78

 I'll check into it tonight.

**Comment by alfg** [comment]
Hi @ShaimaaHamdan, 

I pushed up a fix for this. Can you try again?

https://alfg.github.io/mediacast/#/?drm=none&url=https%3A%2F%2F6954a71498174453877a15012532b59c.azureedge.net%2F085b9f90-988a-42be-82ee-b2961df81c23%2F62f9b6f9-8221-4644-b198-9f9f718e881f.ism%2Fmanifest%28format%3Dm3u8-aapl%29

**Comment by ShaimaaHamdan** [comment]
thanks a lot it is working now !

**Comment by alfg** [comment]
Awesome. Thanks for reporting the issue!
