### ISSUE TITLE
Supporting youtube video urls

### ISSUE THREAD

**Issue by ShaimaaHamdan** [alfg/mediacast#6]
Hello , 
how can  we support runing youtube video like the following Url 
https://www.youtube.com/watch?v=4M5D1r5Yop0&t=128s .

thanks

**Comment by alfg** [comment]
If the video serves an adaptive streaming format like DASH, HLS, or Smooth Streaming, or a container like MP4/WebM, then it may be able to play. However, most services like this will require some type of authentication. I'm not sure if this will work without modification and probably out of the scope of this project.

I think https://github.com/ytdl-org/youtube-dl has some logic around parsing the video page and downloading the stream, which can give an idea of where to get the streaming video url.

**Comment by ShaimaaHamdan** [comment]
Hello thanks for your help , i actually do it another way i user Youtube API and did some customization to the code to support playing the youtube video but i didn't use cast player in case of youtube
https://developers.google.com/youtube/iframe_api_reference
thanks !
